version: "3.9"
services:
  user-service:
    build: user-service
    ports:
    - 8083:8083
    depends_on:
    - mongo
    - kafka
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: user
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: rootpassword
  doctor-service:
    build: doctor-service
    ports:
      - 8081:8081
    depends_on:
      - mongo
      - kafka
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: doctor
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: rootpassword

  payment-service:
    build: capstone-payment-service
    ports:
      - 8086:8086
    depends_on:
      - mongo
      - kafka
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: payment
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: rootpassword
  notification-service:
    build: notification-service
    ports:
      - 8087:8087
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
  rating-service:
    build: rating-service
    ports:
      - 8084:8084
    depends_on:
      - mongo
      - kafka
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: rating
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: rootpassword

  bmc-gateway:
    build: bmc-gateway
    ports:
      - 8085:8085
  appointment-service:
    build: appointment-service
    ports:
      - 8082:8082
    depends_on:
      - mongo
      - kafka
      - mysql
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: appointment
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: rootpassword
      #SPRING_DATASOURCE_URL: jdbc:postgresql://mysql:5432/compose-postgres
      #SPRING_DATASOURCE_USERNAME: compose-postgres
      #SPRING_DATASOURCE_PASSWORD: compose-postgres

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/appointment
      SPRING_DATASOURCE_USERNAME: appointment
      SPRING_DATASOURCE_PASSWORD: appointment
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  mysql:
    image: mysql
    restart: always
    environment:
      #MYSQL_RANDOM_ROOT_PASSWORD: "true"
      #MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      #MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: appointment
      MYSQL_USER: appointment
      MYSQL_PASSWORD: appointment
    volumes:
      - my-db:/var/lib/mysql

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    volumes:
      - "zookeeper_data:/bitnami"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:  {}
  db_data: {}
  my-db: {}
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
