version: "3.9"
services:
  user-service:
    build: user-service
    ports:
    - 8083:8083
    depends_on:
    - mongo
    - kafka
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: user
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: rootpassword
  doctor-service:
    build: doctor-service
    ports:
      - 8081:8081
    depends_on:
      - mongo
      - kafka
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: doctor
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: rootpassword

  payment-service:
    build: capstone-payment-service
    ports:
      - 8086:8086
    depends_on:
      - mongo
      - kafka
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: payment
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: rootpassword
  notification-service:
    build: notification-service
    ports:
      - 8087:8087
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
  rating-service:
    build: rating-service
    ports:
      - 8084:8084
    depends_on:
      - mongo
      - kafka
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: rating
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: rootpassword

  bmc-gateway:
    build: bmc-gateway
    ports:
      - 8085:8085
  appointment-service:
    build: appointment-service
    ports:
      - 8082:8082
    depends_on:
      - mongo
      - kafka
      - db
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: appointment
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: rootpassword
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/compose-postgres
      SPRING_DATASOURCE_USERNAME: compose-postgres
      SPRING_DATASOURCE_PASSWORD: compose-postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:  {}
  db_data: {}
