spring:
  cloud:
    gateway:
      routes:
        - id: doctor-service
          uri: http://doctor-service:8081
          predicates:
            - Path=/doctors/**
        - id: appointment-service
          uri: http://appointment-service:8082
          predicates:
            - Path=/appointments/**
            - Path=/availability/**
        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/users/**
        - id: rating-service
          uri: http://rating-service:8084
          predicates:
            - Path=/ratings/**
        - id: payment-service
          uri: http://payment-service:8086
          predicates:
            - Path=/payments/**
        - id: security-service
          uri: http://security-service:8088
          predicates:
            - Path=/foodDelivery/security/generate-token
server:
  port: 8085