spring:
  cloud:
    gateway:
      routes:
        - id: doctor-service
          uri: http://localhost:8081
          predicates:
            - Path=/doctors/**
        - id: appointment-service
          uri: http://localhost:8082
          predicates:
            - Path=/appointments/**
            - Path=/availability/**
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
        - id: rating-service
          uri: http://localhost:8084
          predicates:
            - Path=/ratings/**
        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/payments/**
        - id: payment-service
          uri: http://localhost:8088
          predicates:
            - Path=/foodDelivery/security/generate-token
server:
  port: 8085